--
-- PostgreSQL database dump
--
-- Dumped from database version 14.5 (Debian 14.5-1.pgdg110+1)
-- Dumped by pg_dump version 14.5 (Debian 14.5-1.pgdg110+1)
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;
--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id bigint NOT NULL
);
ALTER TABLE public.account_emailaddress OWNER TO django_frappe;
--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.account_emailaddress
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.account_emailaddress_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);
ALTER TABLE public.account_emailconfirmation OWNER TO django_frappe;
--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.account_emailconfirmation
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.account_emailconfirmation_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);
ALTER TABLE public.auth_group OWNER TO django_frappe;
--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.auth_group
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.auth_group_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);
ALTER TABLE public.auth_group_permissions OWNER TO django_frappe;
--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.auth_group_permissions
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.auth_group_permissions_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);
ALTER TABLE public.auth_permission OWNER TO django_frappe;
--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.auth_permission
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.auth_permission_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);
ALTER TABLE public.authtoken_token OWNER TO django_frappe;
--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);
ALTER TABLE public.django_admin_log OWNER TO django_frappe;
--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.django_admin_log
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.django_admin_log_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);
ALTER TABLE public.django_content_type OWNER TO django_frappe;
--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.django_content_type
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.django_content_type_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);
ALTER TABLE public.django_migrations OWNER TO django_frappe;
--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.django_migrations
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.django_migrations_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: django_session; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);
ALTER TABLE public.django_session OWNER TO django_frappe;
--
-- Name: django_site; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);
ALTER TABLE public.django_site OWNER TO django_frappe;
--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.django_site
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.django_site_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: frappapi_base; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.frappapi_base (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    stock integer NOT NULL,
    price_per_unit numeric(20, 2) NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    created_on timestamp with time zone NOT NULL,
    decaf boolean NOT NULL
);
ALTER TABLE public.frappapi_base OWNER TO django_frappe;
--
-- Name: frappapi_base_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.frappapi_base
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.frappapi_base_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: frappapi_extradetail; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.frappapi_extradetail (
    id bigint NOT NULL,
    amount integer NOT NULL,
    extras_id bigint NOT NULL,
    frappe_id bigint NOT NULL
);
ALTER TABLE public.frappapi_extradetail OWNER TO django_frappe;
--
-- Name: frappapi_extradetail_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.frappapi_extradetail
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.frappapi_extradetail_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: frappapi_extras; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.frappapi_extras (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    stock integer NOT NULL,
    price_per_unit numeric(20, 2) NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    created_on timestamp with time zone NOT NULL,
    decaf boolean NOT NULL,
    non_dairy boolean NOT NULL,
    gluten_free boolean NOT NULL,
    "limit" integer NOT NULL
);
ALTER TABLE public.frappapi_extras OWNER TO django_frappe;
--
-- Name: frappapi_extras_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.frappapi_extras
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.frappapi_extras_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: frappapi_frappe; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.frappapi_frappe (
    id bigint NOT NULL,
    size integer NOT NULL,
    create_date timestamp with time zone NOT NULL,
    base_id bigint NOT NULL,
    creator_id bigint NOT NULL,
    milk_id bigint NOT NULL
);
ALTER TABLE public.frappapi_frappe OWNER TO django_frappe;
--
-- Name: frappapi_frappe_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.frappapi_frappe
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.frappapi_frappe_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: frappapi_menu; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.frappapi_menu (
    id bigint NOT NULL,
    name character varying(250) NOT NULL,
    photo character varying(100) NOT NULL,
    markup numeric(5, 2) NOT NULL,
    frappe_id bigint NOT NULL
);
ALTER TABLE public.frappapi_menu OWNER TO django_frappe;
--
-- Name: frappapi_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.frappapi_menu
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.frappapi_menu_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: frappapi_milk; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.frappapi_milk (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    stock integer NOT NULL,
    price_per_unit numeric(20, 2) NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    created_on timestamp with time zone NOT NULL,
    non_dairy boolean NOT NULL
);
ALTER TABLE public.frappapi_milk OWNER TO django_frappe;
--
-- Name: frappapi_milk_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.frappapi_milk
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.frappapi_milk_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data text NOT NULL,
    user_id bigint NOT NULL
);
ALTER TABLE public.socialaccount_socialaccount OWNER TO django_frappe;
--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.socialaccount_socialaccount
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.socialaccount_socialaccount_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL
);
ALTER TABLE public.socialaccount_socialapp OWNER TO django_frappe;
--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.socialaccount_socialapp
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.socialaccount_socialapp_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.socialaccount_socialapp_sites (
    id bigint NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);
ALTER TABLE public.socialaccount_socialapp_sites OWNER TO django_frappe;
--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.socialaccount_socialapp_sites
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.socialaccount_socialapp_sites_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer NOT NULL
);
ALTER TABLE public.socialaccount_socialtoken OWNER TO django_frappe;
--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.socialaccount_socialtoken
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.socialaccount_socialtoken_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: users_employee; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.users_employee (
    id bigint NOT NULL,
    hours numeric(100, 2) NOT NULL,
    wage numeric(10, 2) NOT NULL,
    is_cashier boolean NOT NULL,
    is_barista boolean NOT NULL,
    user_id bigint NOT NULL
);
ALTER TABLE public.users_employee OWNER TO django_frappe;
--
-- Name: users_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.users_employee
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.users_employee_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: users_user; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    balance numeric(10, 2) NOT NULL
);
ALTER TABLE public.users_user OWNER TO django_frappe;
--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);
ALTER TABLE public.users_user_groups OWNER TO django_frappe;
--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.users_user_groups
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.users_user_groups_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.users_user
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.users_user_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: django_frappe
--
CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);
ALTER TABLE public.users_user_user_permissions OWNER TO django_frappe;
--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: django_frappe
--
ALTER TABLE public.users_user_user_permissions
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.users_user_user_permissions_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.account_emailaddress (id, email, verified, "primary", user_id)
FROM stdin;
1 admin @admin.com f f 1 \.--
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.account_emailconfirmation (id, created, sent, key, email_address_id)
FROM stdin;
\.--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.auth_group (id, name)
FROM stdin;
\.--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.auth_group_permissions (id, group_id, permission_id)
FROM stdin;
\.--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.auth_permission (id, name, content_type_id, codename)
FROM stdin;
1 Can
add log entry 1 add_logentry 2 Can change log entry 1 change_logentry 3 Can delete log entry 1 delete_logentry 4 Can view log entry 1 view_logentry 5 Can
add permission 2 add_permission 6 Can change permission 2 change_permission 7 Can delete permission 2 delete_permission 8 Can view permission 2 view_permission 9 Can
add group 3 add_group 10 Can change group 3 change_group 11 Can delete group 3 delete_group 12 Can view group 3 view_group 13 Can
add content type 4 add_contenttype 14 Can change content type 4 change_contenttype 15 Can delete content type 4 delete_contenttype 16 Can view content type 4 view_contenttype 17 Can
add session 5 add_session 18 Can change session 5 change_session 19 Can delete session 5 delete_session 20 Can view session 5 view_session 21 Can
add Token 6 add_token 22 Can change Token 6 change_token 23 Can delete Token 6 delete_token 24 Can view Token 6 view_token 25 Can
add token 7 add_tokenproxy 26 Can change token 7 change_tokenproxy 27 Can delete token 7 delete_tokenproxy 28 Can view token 7 view_tokenproxy 29 Can
add site 8 add_site 30 Can change site 8 change_site 31 Can delete site 8 delete_site 32 Can view site 8 view_site 33 Can
add email address 9 add_emailaddress 34 Can change email address 9 change_emailaddress 35 Can delete email address 9 delete_emailaddress 36 Can view email address 9 view_emailaddress 37 Can
add email confirmation 10 add_emailconfirmation 38 Can change email confirmation 10 change_emailconfirmation 39 Can delete email confirmation 10 delete_emailconfirmation 40 Can view email confirmation 10 view_emailconfirmation 41 Can
add social account 11 add_socialaccount 42 Can change social account 11 change_socialaccount 43 Can delete social account 11 delete_socialaccount 44 Can view social account 11 view_socialaccount 45 Can
add social application 12 add_socialapp 46 Can change social application 12 change_socialapp 47 Can delete social application 12 delete_socialapp 48 Can view social application 12 view_socialapp 49 Can
add social application token 13 add_socialtoken 50 Can change social application token 13 change_socialtoken 51 Can delete social application token 13 delete_socialtoken 52 Can view social application token 13 view_socialtoken 53 Can
add base 14 add_base 54 Can change base 14 change_base 55 Can delete base 14 delete_base 56 Can view base 14 view_base 57 Can
add extra detail 15 add_extradetail 58 Can change extra detail 15 change_extradetail 59 Can delete extra detail 15 delete_extradetail 60 Can view extra detail 15 view_extradetail 61 Can
add extras 16 add_extras 62 Can change extras 16 change_extras 63 Can delete extras 16 delete_extras 64 Can view extras 16 view_extras 65 Can
add frappe 17 add_frappe 66 Can change frappe 17 change_frappe 67 Can delete frappe 17 delete_frappe 68 Can view frappe 17 view_frappe 69 Can
add milk 18 add_milk 70 Can change milk 18 change_milk 71 Can delete milk 18 delete_milk 72 Can view milk 18 view_milk 73 Can
add menu 19 add_menu 74 Can change menu 19 change_menu 75 Can delete menu 19 delete_menu 76 Can view menu 19 view_menu 77 Can
add user 20 add_user 78 Can change user 20 change_user 79 Can delete user 20 delete_user 80 Can view user 20 view_user 81 Can
add employee 21 add_employee 82 Can change employee 21 change_employee 83 Can delete employee 21 delete_employee 84 Can view employee 21 view_employee \.--
    -- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: django_frappe
    --
    COPY public.authtoken_token (key, created, user_id)
FROM stdin;
36119bed0810cca0dafcc705ced49504ea16f805 2022 -10 -21 19 :17 :42.374383 + 00 1 \.--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.django_admin_log (
    id,
    action_time,
    object_id,
    object_repr,
    action_flag,
    change_message,
    content_type_id,
    user_id
)
FROM stdin;
\.--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.django_content_type (id, app_label, model)
FROM stdin;
1 admin logentry 2 auth permission 3 auth group 4 contenttypes contenttype 5 sessions session 6 authtoken token 7 authtoken tokenproxy 8 sites site 9 account emailaddress 10 account emailconfirmation 11 socialaccount socialaccount 12 socialaccount socialapp 13 socialaccount socialtoken 14 frappapi base 15 frappapi extradetail 16 frappapi extras 17 frappapi frappe 18 frappapi milk 19 frappapi menu 20 users user 21 users employee \.--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.django_migrations (id, app, name, applied)
FROM stdin;
1 contenttypes 0001_initial 2022 -10 -21 19 :16 :45.844502 + 00 2 contenttypes 0002_remove_content_type_name 2022 -10 -21 19 :16 :45.857018 + 00 3 auth 0001_initial 2022 -10 -21 19 :16 :45.924014 + 00 4 auth 0002_alter_permission_name_max_length 2022 -10 -21 19 :16 :45.933017 + 00 5 auth 0003_alter_user_email_max_length 2022 -10 -21 19 :16 :45.94202 + 00 6 auth 0004_alter_user_username_opts 2022 -10 -21 19 :16 :45.951021 + 00 7 auth 0005_alter_user_last_login_null 2022 -10 -21 19 :16 :45.960533 + 00 8 auth 0006_require_contenttypes_0002 2022 -10 -21 19 :16 :45.966532 + 00 9 auth 0007_alter_validators_add_error_messages 2022 -10 -21 19 :16 :45.977531 + 00 10 auth 0008_alter_user_username_max_length 2022 -10 -21 19 :16 :45.986533 + 00 11 auth 0009_alter_user_last_name_max_length 2022 -10 -21 19 :16 :45.997533 + 00 12 auth 0010_alter_group_name_max_length 2022 -10 -21 19 :16 :46.007531 + 00 13 auth 0011_update_proxy_permissions 2022 -10 -21 19 :16 :46.016532 + 00 14 auth 0012_alter_user_first_name_max_length 2022 -10 -21 19 :16 :46.026533 + 00 15 users 0001_initial 2022 -10 -21 19 :16 :46.115056 + 00 16 account 0001_initial 2022 -10 -21 19 :16 :46.17358 + 00 17 account 0002_email_max_length 2022 -10 -21 19 :16 :46.185577 + 00 18 admin 0001_initial 2022 -10 -21 19 :16 :46.222584 + 00 19 admin 0002_logentry_remove_auto_add 2022 -10 -21 19 :16 :46.231579 + 00 20 admin 0003_logentry_add_action_flag_choices 2022 -10 -21 19 :16 :46.242585 + 00 21 authtoken 0001_initial 2022 -10 -21 19 :16 :46.274102 + 00 22 authtoken 0002_auto_20160226_1747 2022 -10 -21 19 :16 :46.299102 + 00 23 authtoken 0003_tokenproxy 2022 -10 -21 19 :16 :46.307102 + 00 24 frappapi 0001_initial 2022 -10 -21 19 :16 :46.392621 + 00 25 frappapi 0002_initial 2022 -10 -21 19 :16 :46.465132 + 00 26 sessions 0001_initial 2022 -10 -21 19 :16 :46.49513 + 00 27 sites 0001_initial 2022 -10 -21 19 :16 :46.507128 + 00 28 sites 0002_alter_domain_unique 2022 -10 -21 19 :16 :46.527132 + 00 29 socialaccount 0001_initial 2022 -10 -21 19 :16 :46.666182 + 00 30 socialaccount 0002_token_max_lengths 2022 -10 -21 19 :16 :46.692179 + 00 31 socialaccount 0003_extra_data_default_dict 2022 -10 -21 19 :16 :46.70518 + 00 \.--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.django_session (session_key, session_data, expire_date)
FROM stdin;
7hpbs8hzw0enm58xho0aqngluruhhdfc.eJxVjMsOwiAQRf - FtSEMRR4u3fsNZGCmUjWQlHZl_HfbpAvd3nPOfYuI61Li2nmOE4mLAHH63RLmJ9cd0APrvcnc6jJPSe6KPGiXt0b8uh7u30HBXrZakw4WksNBOfRKazbEfuSBRjCJ8ayVtYQe1LB5jr0DGzi4pDJl8EZ8vtXUN3I :1olxWY :00Vts1JGTtzx3HSa8QDIQLKJFGaLj7Y1PGUZUSV - HLg 2022 -11 -04 19 :17 :42.415383 + 00 \.--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.django_site (id, domain, name)
FROM stdin;
1 example.com example.com \.--
-- Data for Name: frappapi_base; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.frappapi_base (
    id,
    name,
    stock,
    price_per_unit,
    updated_on,
    created_on,
    decaf
)
FROM stdin;
1 Coffee 999999999 1.00 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 f 2 Cream 999999999 1.50 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t 3 Mocha 999999999 2.50 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t \.--
-- Data for Name: frappapi_extradetail; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.frappapi_extradetail (id, amount, extras_id, frappe_id)
FROM stdin;
\.--
-- Data for Name: frappapi_extras; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.frappapi_extras (
    id,
    name,
    stock,
    price_per_unit,
    updated_on,
    created_on,
    decaf,
    non_dairy,
    gluten_free,
    "limit"
)
FROM stdin;
1 Secret Sauce 10 20.00 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t f f 1 2 Vanilla 1000 0.30 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t t t 4 3 Caramel 1000 0.30 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t t t 5 4 Pumpkin Sauce 10 0.80 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t t t 3 5 Macha 1000 0.45 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t t t 2 6 Expresso Shot 10000 0.45 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t t t 3 7 Chocolate Drizzle 1550 0.70 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t t t 1 8 Oreos 10000 9.00 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t f f 35 9 Whip Cream 1000 0.45 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t f t 2 10 Sugar 1000 0.45 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t t t 3 \.--
-- Data for Name: frappapi_frappe; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.frappapi_frappe (
    id,
    size,
    create_date,
    base_id,
    creator_id,
    milk_id
)
FROM stdin;
\.--
-- Data for Name: frappapi_menu; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.frappapi_menu (id, name, photo, markup, frappe_id)
FROM stdin;
\.--
-- Data for Name: frappapi_milk; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.frappapi_milk (
    id,
    name,
    stock,
    price_per_unit,
    updated_on,
    created_on,
    non_dairy
)
FROM stdin;
1 Whole Milk 1000 2.05 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 f 2 Soy Milk 1000 5.05 2022 -10 -10 20 :19 :20.523 + 00 2022 -10 -10 20 :19 :20.523 + 00 t \.--
-- Data for Name: socialaccount_socialaccount; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.socialaccount_socialaccount (
    id,
    provider,
    uid,
    last_login,
    date_joined,
    extra_data,
    user_id
)
FROM stdin;
\.--
-- Data for Name: socialaccount_socialapp; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.socialaccount_socialapp (id, provider, name, client_id, secret, key)
FROM stdin;
\.--
-- Data for Name: socialaccount_socialapp_sites; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.socialaccount_socialapp_sites (id, socialapp_id, site_id)
FROM stdin;
\.--
-- Data for Name: socialaccount_socialtoken; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.socialaccount_socialtoken (
    id,
    token,
    token_secret,
    expires_at,
    account_id,
    app_id
)
FROM stdin;
\.--
-- Data for Name: users_employee; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.users_employee (id, hours, wage, is_cashier, is_barista, user_id)
FROM stdin;
\.--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.users_user (
    id,
    password,
    last_login,
    is_superuser,
    first_name,
    last_name,
    is_staff,
    is_active,
    date_joined,
    email,
    balance
)
FROM stdin;
1 pbkdf2_sha256 $390000$MTFhT8v5xdLvZv1QTpmHY5$xkhOQ / DtnIm1eKOFW0grtjGzNQDxOW9hfZE6rWWit2Y = 2022 -10 -21 19 :17 :42.408384 + 00 t t t 2022 -10 -21 19 :17 :36.209192 + 00 admin @admin.com 0.00 \.--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.users_user_groups (id, user_id, group_id)
FROM stdin;
\.--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: django_frappe
--
COPY public.users_user_user_permissions (id, user_id, permission_id)
FROM stdin;
\.--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 1, true);
--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval(
        'public.account_emailconfirmation_id_seq',
        1,
        false
    );
--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);
--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);
--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.auth_permission_id_seq', 84, true);
--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);
--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.django_content_type_id_seq', 21, true);
--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.django_migrations_id_seq', 31, true);
--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);
--
-- Name: frappapi_base_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.frappapi_base_id_seq', 3, true);
--
-- Name: frappapi_extradetail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.frappapi_extradetail_id_seq', 1, false);
--
-- Name: frappapi_extras_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.frappapi_extras_id_seq', 10, true);
--
-- Name: frappapi_frappe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.frappapi_frappe_id_seq', 1, false);
--
-- Name: frappapi_menu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.frappapi_menu_id_seq', 1, false);
--
-- Name: frappapi_milk_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.frappapi_milk_id_seq', 2, true);
--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval(
        'public.socialaccount_socialaccount_id_seq',
        1,
        false
    );
--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval(
        'public.socialaccount_socialapp_id_seq',
        1,
        false
    );
--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval(
        'public.socialaccount_socialapp_sites_id_seq',
        1,
        false
    );
--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval(
        'public.socialaccount_socialtoken_id_seq',
        1,
        false
    );
--
-- Name: users_employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.users_employee_id_seq', 1, false);
--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);
--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval('public.users_user_id_seq', 1, true);
--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_frappe
--
SELECT pg_catalog.setval(
        'public.users_user_user_permissions_id_seq',
        1,
        false
    );
--
-- Name: account_emailaddress account_emailaddress_email_key; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.account_emailaddress
ADD CONSTRAINT account_emailaddress_email_key UNIQUE (email);
--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.account_emailaddress
ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);
--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.account_emailconfirmation
ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);
--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.account_emailconfirmation
ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);
--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.auth_group
ADD CONSTRAINT auth_group_name_key UNIQUE (name);
--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.auth_group_permissions
ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);
--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.auth_group_permissions
ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);
--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.auth_group
ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);
--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.auth_permission
ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);
--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.auth_permission
ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);
--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.authtoken_token
ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);
--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.authtoken_token
ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);
--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.django_admin_log
ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);
--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.django_content_type
ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);
--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.django_content_type
ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);
--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.django_migrations
ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);
--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.django_session
ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);
--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.django_site
ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);
--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.django_site
ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);
--
-- Name: frappapi_base frappapi_base_name_key; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_base
ADD CONSTRAINT frappapi_base_name_key UNIQUE (name);
--
-- Name: frappapi_base frappapi_base_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_base
ADD CONSTRAINT frappapi_base_pkey PRIMARY KEY (id);
--
-- Name: frappapi_extradetail frappapi_extradetail_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_extradetail
ADD CONSTRAINT frappapi_extradetail_pkey PRIMARY KEY (id);
--
-- Name: frappapi_extras frappapi_extras_name_key; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_extras
ADD CONSTRAINT frappapi_extras_name_key UNIQUE (name);
--
-- Name: frappapi_extras frappapi_extras_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_extras
ADD CONSTRAINT frappapi_extras_pkey PRIMARY KEY (id);
--
-- Name: frappapi_frappe frappapi_frappe_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_frappe
ADD CONSTRAINT frappapi_frappe_pkey PRIMARY KEY (id);
--
-- Name: frappapi_menu frappapi_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_menu
ADD CONSTRAINT frappapi_menu_pkey PRIMARY KEY (id);
--
-- Name: frappapi_milk frappapi_milk_name_key; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_milk
ADD CONSTRAINT frappapi_milk_name_key UNIQUE (name);
--
-- Name: frappapi_milk frappapi_milk_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_milk
ADD CONSTRAINT frappapi_milk_pkey PRIMARY KEY (id);
--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialaccount
ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);
--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialaccount
ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);
--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialapp_sites
ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);
--
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialapp
ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);
--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialapp_sites
ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);
--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialtoken
ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);
--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialtoken
ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);
--
-- Name: users_employee users_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_employee
ADD CONSTRAINT users_employee_pkey PRIMARY KEY (id);
--
-- Name: users_employee users_employee_user_id_key; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_employee
ADD CONSTRAINT users_employee_user_id_key UNIQUE (user_id);
--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user
ADD CONSTRAINT users_user_email_key UNIQUE (email);
--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user_groups
ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);
--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user_groups
ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);
--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user
ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);
--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user_user_permissions
ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);
--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user_user_permissions
ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);
--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);
--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);
--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);
--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);
--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);
--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);
--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);
--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);
--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);
--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);
--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);
--
-- Name: frappapi_base_name_6cfe4319_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX frappapi_base_name_6cfe4319_like ON public.frappapi_base USING btree (name varchar_pattern_ops);
--
-- Name: frappapi_extradetail_extras_id_e84098de; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX frappapi_extradetail_extras_id_e84098de ON public.frappapi_extradetail USING btree (extras_id);
--
-- Name: frappapi_extradetail_frappe_id_6a05837b; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX frappapi_extradetail_frappe_id_6a05837b ON public.frappapi_extradetail USING btree (frappe_id);
--
-- Name: frappapi_extras_name_2ccfa242_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX frappapi_extras_name_2ccfa242_like ON public.frappapi_extras USING btree (name varchar_pattern_ops);
--
-- Name: frappapi_frappe_base_id_9e1e9b28; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX frappapi_frappe_base_id_9e1e9b28 ON public.frappapi_frappe USING btree (base_id);
--
-- Name: frappapi_frappe_creator_id_f2d801e8; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX frappapi_frappe_creator_id_f2d801e8 ON public.frappapi_frappe USING btree (creator_id);
--
-- Name: frappapi_frappe_milk_id_b04614d2; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX frappapi_frappe_milk_id_b04614d2 ON public.frappapi_frappe USING btree (milk_id);
--
-- Name: frappapi_menu_frappe_id_7fffe6a2; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX frappapi_menu_frappe_id_7fffe6a2 ON public.frappapi_menu USING btree (frappe_id);
--
-- Name: frappapi_milk_name_2a5a6671_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX frappapi_milk_name_2a5a6671_like ON public.frappapi_milk USING btree (name varchar_pattern_ops);
--
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);
--
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);
--
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);
--
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);
--
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);
--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);
--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);
--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);
--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);
--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: django_frappe
--
CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);
--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.account_emailaddress
ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.account_emailconfirmation
ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.auth_group_permissions
ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.auth_group_permissions
ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.auth_permission
ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.authtoken_token
ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.django_admin_log
ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.django_admin_log
ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: frappapi_extradetail frappapi_extradetail_extras_id_e84098de_fk_frappapi_extras_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_extradetail
ADD CONSTRAINT frappapi_extradetail_extras_id_e84098de_fk_frappapi_extras_id FOREIGN KEY (extras_id) REFERENCES public.frappapi_extras(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: frappapi_extradetail frappapi_extradetail_frappe_id_6a05837b_fk_frappapi_frappe_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_extradetail
ADD CONSTRAINT frappapi_extradetail_frappe_id_6a05837b_fk_frappapi_frappe_id FOREIGN KEY (frappe_id) REFERENCES public.frappapi_frappe(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: frappapi_frappe frappapi_frappe_base_id_9e1e9b28_fk_frappapi_base_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_frappe
ADD CONSTRAINT frappapi_frappe_base_id_9e1e9b28_fk_frappapi_base_id FOREIGN KEY (base_id) REFERENCES public.frappapi_base(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: frappapi_frappe frappapi_frappe_creator_id_f2d801e8_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_frappe
ADD CONSTRAINT frappapi_frappe_creator_id_f2d801e8_fk_users_user_id FOREIGN KEY (creator_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: frappapi_frappe frappapi_frappe_milk_id_b04614d2_fk_frappapi_milk_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_frappe
ADD CONSTRAINT frappapi_frappe_milk_id_b04614d2_fk_frappapi_milk_id FOREIGN KEY (milk_id) REFERENCES public.frappapi_milk(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: frappapi_menu frappapi_menu_frappe_id_7fffe6a2_fk_frappapi_frappe_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.frappapi_menu
ADD CONSTRAINT frappapi_menu_frappe_id_7fffe6a2_fk_frappapi_frappe_id FOREIGN KEY (frappe_id) REFERENCES public.frappapi_frappe(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialtoken
ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialtoken
ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialapp_sites
ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialapp_sites
ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.socialaccount_socialaccount
ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: users_employee users_employee_user_id_6131bb7a_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_employee
ADD CONSTRAINT users_employee_user_id_6131bb7a_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user_groups
ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user_groups
ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user_user_permissions
ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: django_frappe
--
ALTER TABLE ONLY public.users_user_user_permissions
ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;
--
-- PostgreSQL database dump complete
- -