# Generated by Django 4.1.2 on 2022-10-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("stock", models.IntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("decaf", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExtraDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Extras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("stock", models.IntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("decaf", models.BooleanField(default=True)),
                ("non_dairy", models.BooleanField(default=True)),
                ("gluten_free", models.BooleanField(default=True)),
                ("limit", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Frappe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("markup", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "size",
                    models.IntegerField(
                        choices=[(1, "Small"), (2, "Medium"), (3, "Large")]
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="frappapi.base"
                    ),
                ),
                (
                    "extras",
                    models.ManyToManyField(
                        blank=True, through="frappapi.ExtraDetail", to="frappapi.extras"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Milk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("stock", models.IntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("non_dairy", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="uploads")),
                (
                    "frappe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frappapi.frappe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="frappe",
            name="milk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="frappapi.milk"
            ),
        ),
        migrations.AddField(
            model_name="extradetail",
            name="extras",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="frappapi.extras"
            ),
        ),
        migrations.AddField(
            model_name="extradetail",
            name="frappe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="frappapi.frappe"
            ),
        ),
    ]
