# Generated by Django 4.1.2 on 2022-10-23 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stock', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('decaf', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stock', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('decaf', models.BooleanField(default=True)),
                ('non_dairy', models.BooleanField(default=True)),
                ('gluten_free', models.BooleanField(default=True)),
                ('limit', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frappe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frappapi.base')),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stock', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('non_dairy', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='uploads')),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('frappe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frappapi.frappe')),
            ],
        ),
    ]
