# Generated by Django 4.1.2 on 2022-11-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frappapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frappe",
            name="menu_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="menu_key",
                to="frappapi.menu",
            ),
        ),
    ]
