# Generated by Django 4.1.2 on 2022-10-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frappapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frappe",
            name="extras",
            field=models.ManyToManyField(
                blank=True,
                related_name="details",
                through="frappapi.ExtraDetail",
                to="frappapi.extras",
            ),
        ),
    ]
