# Generated by Django 4.1.3 on 2022-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frappapi", "0002_alter_frappe_menu_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="markup",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5
            ),
        ),
    ]
