# Generated by Django 4.1.2 on 2022-11-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frappapi", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frappe",
            name="menu_key",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_key",
                to="frappapi.menu",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu",
            name="frappe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="frappapi.frappe"
            ),
        ),
    ]
