# Generated by Django 4.1.2 on 2022-11-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappapi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
