# Generated by Django 4.1.2 on 2022-11-15 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frappapi', '0003_menu_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frappe',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frappapi.base'),
        ),
        migrations.AlterField(
            model_name='frappe',
            name='milk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frappapi.milk'),
        ),
        migrations.AlterField(
            model_name='frappe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='frappe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frappapi.frappe'),
        ),
    ]
