# Generated by Django 4.1.2 on 2022-10-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappapi', '0003_frappe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='frappe',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
