# Generated by Django 4.1.3 on 2022-11-30 22:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frappapi", "0003_alter_menu_markup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="markup",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("2.29999999999999982236431605997495353221893310546875"),
                max_digits=5,
            ),
        ),
    ]
