# Generated by Django 4.1.2 on 2022-11-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappapi', '0004_alter_frappe_menu_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='frappe',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Completed')], default=2),
            preserve_default=False,
        ),
    ]
