# Generated by Django 4.1.2 on 2022-11-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappapi', '0005_frappe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frappe',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Completed')], default=1),
        ),
    ]
