# Generated by Django 4.1.2 on 2022-10-20 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "wage",
                    models.DecimalField(decimal_places=2, default=14.95, max_digits=10),
                ),
                ("is_cashier", models.BooleanField(default=False)),
                ("is_barista", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
